### ISSUE TITLE
Windows go missing

### ISSUE THREAD

**Issue by rGunti** [dalyIsaac/Whim#781] opened 2024-01-15 12:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Behavior

In certain situations when switching between spaces (haven't yet figured out when exactly when), windows can go missing. The app will not show in ALT+TAB or the Taskbar, but the app is still running (when checking task manager). Depending on the application, I can either restore the window by triggering full screen, force-activating it through a Window menu in the app itself, terminate the app through another instance or kill it through Task manager.

### Config

```csharp
#nullable enable
#r "C:\Program Files\Whim\whim.dll"
#r "C:\Program Files\Whim\plugins\Whim.Bar\Whim.Bar.dll"
#r "C:\Program Files\Whim\plugins\Whim.CommandPalette\Whim.CommandPalette.dll"
#r "C:\Program Files\Whim\plugins\Whim.FloatingLayout\Whim.FloatingLayout.dll"
#r "C:\Program Files\Whim\plugins\Whim.FocusIndicator\Whim.FocusIndicator.dll"
#r "C:\Program Files\Whim\plugins\Whim.Gaps\Whim.Gaps.dll"
#r "C:\Program Files\Whim\plugins\Whim.LayoutPreview\Whim.LayoutPreview.dll"
#r "C:\Program Files\Whim\plugins\Whim.SliceLayout\Whim.SliceLayout.dll"
#r "C:\Program Files\Whim\plugins\Whim.TreeLayout\Whim.TreeLayout.dll"
#r "C:\Program Files\Whim\plugins\Whim.TreeLayout.Bar\Whim.TreeLayout.Bar.dll"
#r "C:\Program Files\Whim\plugins\Whim.TreeLayout.CommandPalette\Whim.TreeLayout.CommandPalette.dll"
#r "C:\Program Files\Whim\plugins\Whim.Updater\Whim.Updater.dll"

using System;
using System.Linq;
using System.Collections.Generic;
using Whim;
using Whim.Bar;
using Whim.CommandPalette;
using Whim.FloatingLayout;
using Whim.FocusIndicator;
using Whim.Gaps;
using Whim.LayoutPreview;
using Whim.SliceLayout;
using Whim.TreeLayout;
using Whim.TreeLayout.Bar;
using Whim.TreeLayout.CommandPalette;
using Whim.Updater;
using Windows.Win32.UI.Input.KeyboardAndMouse;
using Microsoft.UI;
using Microsoft.UI.Xaml.Media;

const string WORKSPACE_COMMUNICATION = "comms";
const string WORKSPACE_WORK = "work";
const string WORKSPACE_SECONDARY = "secondary";
const string WORKSPACE_AUX = "aux";

var communicationProcesses = new string[]
{
	"teams.exe",
	"outlook.exe",
	"obsidian.exe"
}.ToHashSet();
var workProcesses = new string[]
{
	"code.exe",
	"rider64.exe",
}.ToHashSet();
var secondaryProcesses = new string[]
{
	"vivaldi.exe",
}.ToHashSet();

var floatingProcesses = new string[]
{
	"greenshot.exe",
	"sharex.exe"
}.ToHashSet();

/// <summary>
/// This is what's called when Whim is loaded.
/// </summary>
/// <param name="context"></param>
void DoConfig(IContext context)
{
	context.Logger.Config = new LoggerConfig();

	// Bar plugin.
	List<BarComponent> leftComponents = new() { WorkspaceWidget.CreateComponent() };
	List<BarComponent> centerComponents = new() { FocusedWindowWidget.CreateComponent() };
	List<BarComponent> rightComponents = new()
	{
		BatteryWidget.CreateComponent(),
		ActiveLayoutWidget.CreateComponent(),
		DateTimeWidget.CreateComponent(format: "HH:mm:ss")
	};

	BarConfig barConfig = new(leftComponents, centerComponents, rightComponents);
	BarPlugin barPlugin = new(context, barConfig);
	context.PluginManager.AddPlugin(barPlugin);

	// Gap plugin.
	GapsConfig gapsConfig = new() { OuterGap = 0, InnerGap = 10 };
	GapsPlugin gapsPlugin = new(context, gapsConfig);
	context.PluginManager.AddPlugin(gapsPlugin);

	// Floating window plugin.
	FloatingLayoutPlugin floatingLayoutPlugin = new(context);
	context.PluginManager.AddPlugin(floatingLayoutPlugin);

	// // Focus indicator.
	// FocusIndicatorConfig focusIndicatorConfig = new() { Color = new SolidColorBrush(Colors.Red), FadeEnabled = true, BorderSize = 2 };
	// FocusIndicatorPlugin focusIndicatorPlugin = new(context, focusIndicatorConfig);
	// context.PluginManager.AddPlugin(focusIndicatorPlugin);

	// Command palette.
	CommandPaletteConfig commandPaletteConfig = new(context);
	CommandPalettePlugin commandPalettePlugin = new(context, commandPaletteConfig);
	context.PluginManager.AddPlugin(commandPalettePlugin);

	// Slice layout.
	SliceLayoutPlugin sliceLayoutPlugin = new(context);
	context.PluginManager.AddPlugin(sliceLayoutPlugin);

	// Tree layout.
	TreeLayoutPlugin treeLayoutPlugin = new(context);
	context.PluginManager.AddPlugin(treeLayoutPlugin);

	// Tree layout bar.
	TreeLayoutBarPlugin treeLayoutBarPlugin = new(treeLayoutPlugin);
	context.PluginManager.AddPlugin(treeLayoutBarPlugin);
	rightComponents.Add(treeLayoutBarPlugin.CreateComponent());

	// Tree layout command palette.
	TreeLayoutCommandPalettePlugin treeLayoutCommandPalettePlugin = new(context, treeLayoutPlugin, commandPalettePlugin);
	context.PluginManager.AddPlugin(treeLayoutCommandPalettePlugin);

	// Layout preview.
	LayoutPreviewPlugin layoutPreviewPlugin = new(context);
	context.PluginManager.AddPlugin(layoutPreviewPlugin);

	// Updater.
	UpdaterConfig updaterConfig = new() { ReleaseChannel = ReleaseChannel.Beta };
	UpdaterPlugin updaterPlugin = new(context, updaterConfig);
	context.PluginManager.AddPlugin(updaterPlugin);

	// Set up workspaces.
	context.WorkspaceManager.Add(WORKSPACE_COMMUNICATION);
	context.WorkspaceManager.Add(WORKSPACE_WORK);
	context.WorkspaceManager.Add(WORKSPACE_SECONDARY);
	context.WorkspaceManager.Add(WORKSPACE_AUX);

	// Set up layout engines.
	context.WorkspaceManager.CreateLayoutEngines = () => new CreateLeafLayoutEngine[]
	{
		(id) => SliceLayouts.CreateMultiColumnLayout(context, sliceLayoutPlugin, id, 1, 2, 0),
		(id) => SliceLayouts.CreatePrimaryStackLayout(context, sliceLayoutPlugin, id),
		(id) => SliceLayouts.CreateSecondaryPrimaryLayout(context, sliceLayoutPlugin, id),
		(id) => new FocusLayoutEngine(id),
		(id) => new TreeLayoutEngine(context, treeLayoutPlugin, id),
		(id) => new ColumnLayoutEngine(id)
	};

	// Routing ***
	context.RouterManager.Add((window) =>
	{
		var process = window.ProcessFileName.ToLowerInvariant();
		if (communicationProcesses.Contains(process))
		{
			return context.WorkspaceManager.TryGet(WORKSPACE_COMMUNICATION);
		}
		else if (workProcesses.Contains(process))
		{
			return context.WorkspaceManager.TryGet(WORKSPACE_WORK);
		}
		else if (secondaryProcesses.Contains(process))
		{
			return context.WorkspaceManager.TryGet(WORKSPACE_SECONDARY);
		}
		return null;
	});

	foreach (var process in floatingProcesses)
	{
		context.FilterManager.AddProcessFileNameFilter(process);
	}

	// Commands ***
	//context.CommandManager.Add(
	//	identifier: "rg_sort_communication",
	//	title: "",
	//	callback: () =>
	//	{
	//	}
	//);
}

// We return doConfig here so that Whim can call it when it loads.
return DoConfig;
```

### Environment

- Windows: Windows 11 23H2 (OS Build 22631.3007)
- Architecture: x86_64
- Whim: 0.4.14

### Steps To Reproduce

Exact steps to be provided, wasn't able to exactly figure out under what conditions this happens

**Comment by dalyIsaac** [comment] 2024-01-16 09:21
I've encountered a similar issue to this, and it seemed related to being unable to acquire monitor information.

Does it occur often, and what sort of windows get lost?

**Comment by rGunti** [comment] 2024-01-17 12:39
Just happened again after I restarted Whim to apply a config change. It seems to affect mostly windows that are not in any visible workspace at the time Whim is restarted.

**Comment by gplusplus314** [comment] 2024-01-17 19:47
I'm running the main branch and something is weird since #780. I'm experiencing something similar to the OP. These are the best reproduction steps I can come up with, but it doesn't repro every time. Once it does, the window is permanently lost.

0. Start in workspace 1.
1. Create an instance of Firefox, instance A.
2. Open a PWA powered by Firefox (Firefox PWA addon, in my case it's Slack). I'll call this instance B.
3. Move instance B to workspace 2.
4. Switch to workspace 2. Use your Firefox PWA a bit.
5. Switch to workspace 1. Use Firefox a bit.
6. Keep alternating between 4 and 5 until one of the windows disappears.

Interestingly, the border highlight window remains in place, so I have a giant (in my case, purple) rectangle flashbanging my retinas. ;)

**Comment by rGunti** [comment] 2024-01-18 09:12
I was just able to reproduce it, when updating to the latest release. I had an application open on a non-visible workspace. After Whim was restarted, I switched to that Workspace and found it to be empty. I will test further when time allows. Currently running on [v0.4.19](https://github.com/dalyIsaac/Whim/releases/tag/v0.4.19-alpha%2B8bc74632)

**Comment by dalyIsaac** [comment] 2024-01-21 21:23
I just encountered this randomly, but the logs didn't help. I'll add some more logging when setting the window positions to see if I can find more.

**Comment by dalyIsaac** [comment] 2024-01-22 11:34
I've identified an issue with `TreeLayoutEngine.RemoveWindow` obliterating minimized windows while removing the sole visible window in the engine. Depending on how I feel, I may include the fix for this with #789.

I have a suspicion there may be a separate issue too - I'll continue trying to hunt it down.

**Comment by dalyIsaac** [comment] 2024-01-23 07:54
The `TreeLayoutEngine` fix is now in - hopefully that helps.

**Comment by dalyIsaac** [comment] 2024-02-07 10:31
I haven't encountered this for a few weeks, so I'm (optimistically) closing this issue.

**Closed by dalyIsaac** 2024-02-07 10:31 UTC
Labels: bug, triage
